### ISSUE TITLE
Decimal Double precision numbers 

### ISSUE THREAD

**Issue by mahasch** [LangProc/langproc-2021-lab#1]
Hello, I wanted to ask what does decimal double-precision number mean? Is it only referring to the amount of decimal digits it can have ->so 16?

**Comment by sts219** [comment]
It refers to the type of the floating point number. In C++, the `double` type uses twice as many bits as the `float` type, and so it is a "double-precision number".

**Comment by johnwickerson** [comment]
Typically a `float` number uses 32 bits and a `double` number uses 64 bits.
