### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by Cathy-DYX** [LangProc/langproc-2021-lab#11]
Hello, I got an error when running the code through bash script.
When entering '_make histogram -B_' followed by '_cat test/in/01.txt | ./histogram_' directly into terminal, I got the output as expected. However, when running the bash script '_./test_lexer.sh_', I got the following error:
![image](https://user-images.githubusercontent.com/62194910/150656937-ee066e3a-3f32-4713-a496-1074989ffce2.png)
I tried entering 'chmod u+x histogram' before running the bash script, but it doesn't seem to solve the error. Since it's working fine when directly running the command through terminal, I'm not sure what causes this error.

**Comment by ymherklotz** [comment]
Hi, that is indeed very strange.

The only thing I can think of is that somehow the recompilation that
`./test_lexer.sh` is doing is failing.

Could you execute the following commands one after another, and then attach the
langproc-11.log file that will be produced?

    make -B histogram >>langproc-11.log 2>&1
    { cat test/in/01.txt | ./histogram } >>langproc-11.log 2>&1
    ./test_lexer.sh >>langproc-11.log 2>&1

**Comment by Cathy-DYX** [comment]
I executed the commands like this:
![image](https://user-images.githubusercontent.com/62194910/150676793-cbaefc45-4b60-464c-a307-e358310bd112.png)
and this is what the langproc-11.log file contains:
![image](https://user-images.githubusercontent.com/62194910/150676820-581b3b8b-55ee-43f6-a7ed-e07eb2b0ac06.png)

**Comment by ymherklotz** [comment]
Hi, sorry, something seems to have gone wrong.  Could you just run:

```
 ./test_lexer.sh >>langproc-11.log 2>&1
```

again and send the log file?

**Comment by Cathy-DYX** [comment]
Here is the log file
[langproc-11.log](https://github.com/LangProc/langproc-2021-lab/files/7920480/langproc-11.log)
and all the *.stderr.txt files says '_./test_lexer.sh: line 42: ./histogram: Permission denied_'

**Comment by ymherklotz** [comment]
Hi, thanks to a lot of help by @BPulmannova, I think we have found the issue.  It seems like Windows is messing up the permissions of the Vagrant machine because of the synced directory... If you copy it inside of the machine and test it, it should work:

``` shell
cp -r /vagrant ~/langproc
cd ~/langproc/1-*
chmod +x test_lexer.sh
./test_lexer.sh
```

However, doing this everytime seems like it will be annoying if you are editing files in windows and using the sync to the VM, and you will have to edit files within the VM otherwise.

My advice would be to use [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/install), which should not have the issue above. You can then clone the repository into WSL, and work from there.  You will also have to run the following commands in WSL to set up the environment properly:

``` shell
sudo apt-get update

# Standard build tools
sudo apt-get -y install g++ gdb make dos2unix git

# Compiler build tools
sudo apt-get -y install bison flex

# MIPS cross-compiler stuff
sudo apt-get -y install g++-mips-linux-gnu gdb-multiarch

# QEMU run-time emulator
sudo apt-get -y install qemu
```

**Comment by ymherklotz** [comment]
If you are using WSL, you can then always check before submitting that everything still works in Vagrant by using the *copy* method above.

**Comment by Cathy-DYX** [comment]
Thank you so much! It's working fine now!

**Comment by Gandinator123** [comment]
Hi, I still get the permission denied after running this. 

> Hi, thanks to a lot of help by @BPulmannova, I think we have found the issue. It seems like Windows is messing up the permissions of the Vagrant machine because of the synced directory... If you copy it inside of the machine and test it, it should work:
> 
> ```shell
> cp -r /vagrant ~/langproc
> cd ~/langproc/1-*
> chmod +x test_lexer.sh
> ./test_lexer.sh
> ```
>

**Comment by ymherklotz** [comment]
Hi @Gandinator123, could you post more details about the problem? Where exactly you see the errors?

**Comment by Gandinator123** [comment]
> ```shell
> sudo apt-get -y install g++ gdb make dos2unix git
> ```

The errors are in some of the stderr files.
![image](https://user-images.githubusercontent.com/65455744/151570213-d54070c6-a5b6-424d-b4ab-33b9a9031c69.png)

It is strange because not all the files have this error and some are passing. On my Ubuntu WSL all my tests pass.

**Comment by Gandinator123** [comment]
> > Hi @Gandinator123, could you post more details about the problem? Where exactly you see the errors?
> 
> The errors are in some of the stderr files. ![image](https://user-images.githubusercontent.com/65455744/151570213-d54070c6-a5b6-424d-b4ab-33b9a9031c69.png)
> 
> It is strange because not all the files have this error and some are passing. On my Ubuntu WSL all my tests pass.

Actually, I deleted the copied files and recopied them and now it works in vagrant. Thanks.

**Comment by Strikewind** [comment]
![image](https://user-images.githubusercontent.com/93332879/152605571-f093c193-267c-41e4-95ae-986ff9c54fba.png)
Someone said I should post this here. Adding this to the Vagrantfile allows all created files to have execute permissions.
```
config.vm.synced_folder ".", "/vagrant",
    mount_options: ["dmode=775,fmode=777"]
```
