### ISSUE TITLE
Question about Decimal

### ISSUE THREAD

**Issue by Aeroking21** [LangProc/langproc-2021-lab#13]
Hello,

The definition of **Decimal** is given as:
 - A **decimal** is a sequence of one or more decimal digits, preceded by an optional `-` sign, and optionally followed by a `.` sign and zero or more decimal digits. It should be interpreted as a decimal double-precision number.

I am slightly confused as to the meaning of "optionally followed by a `.` sign and zero or more decimal digits".
1. Does this mean that the optionality refers to both the `.` and zero or more decimal digits or just `.` ? 
2. If a number such as `5.` is provided should this just be tokenized to `5` ?

**Comment by BPulmannova** [comment]
1. Although English-wise the optionality feels (at least to me) more naturally referring to both, using the extended regexes from lectures, this question comes down to how is
[0-9]<sup>+</sup>.<sup>?</sup>[0-9]<sup>\*</sup>
different from
[0-9]<sup>+</sup>(.[0-9]<sup>\*</sup>)<sup>?</sup>
(omitting the minus sign)
Can you come up if a word that is accepted by one but not the other?
2. If `5.` would match the pattern defined for **decimal**, lexer - pursuing the longest pattern - would choose that over a single `5`
If the question was more along the lines of *"writing five as 5. is odd"* then maybe the fact that C/C++ will gladly let you initialise a double-precision number as `5.` might be comforting.

**Comment by Aeroking21** [comment]
That clears things up, I can't seem to find and differences between the following 2 regexes, which will cause a decimal to be accepted by one regex but not the other.

**Comment by BPulmannova** [comment]
The first regex is more generous in the way it let's you omit `.` but keep [0-9]<sup>*</sup> - but as you found, this case will get caught by [0-9]<sup>+</sup> anyway.
