### ISSUE TITLE
Test case 19 reference output 

### ISSUE THREAD

**Issue by ozeidan9** [LangProc/langproc-2021-lab#14]
1. The reference output for test case 19 (right window of image) ignores the whitespace from the last word in line 5 of the input file (middle window). Shouldn't this be incorrect since from the specification a word could be decribed as '[*1 space*]', therefore shouldn't the correct word output be as shown in the left window of the image below?

<img width="663" alt="Screenshot 2022-01-24 at 12 11 25 pm" src="https://user-images.githubusercontent.com/94687744/150781668-d2296ed9-dad1-49da-b456-ae3a735b9162.png">

2. The reference output counts 4 '[]' words, but shouldn't this be counted 3 times from the input text?

**Comment by BPulmannova** [comment]
Combining the following two lines from the specification,

- _A word can also be any sequence of 8-bit characters beginning with [, and ending at the next ]. The word itself does not include the surrounding`[` and `]` characters. You can assume that such a sequence will never span a line-break._
- All other characters should not be counted (and should not appear in the output).

can you see why `[]` is counted 4-times, and could applying this on the 5th line of the input also answer your first question?
