### ISSUE TITLE
Issue with the auto sort_order function - Lab 1

### ISSUE THREAD

**Issue by ThrasherA** [LangProc/langproc-2021-lab#15]
Hello, 

I am having an issue with the following function:

<img width="1032" alt="Screenshot 2022-01-24 at 13 51 50" src="https://user-images.githubusercontent.com/93782946/150795055-7230314b-2ad7-443d-be60-5bd69972de07.png">

I am unsure of what to do to fix this and need some guidance.
I am on Mac OS and this is within Visual Studio Code.

Thanks

**Comment by ymherklotz** [comment]
Hi, this should still compile on the commandline though when you type `make`, at least if you are using **Vagrant**.

In this case, it just seems like the compiler used by VSCode when analysing the code is using the wrong compiler flags (probably missing `-std=c++11`).

In addition to that, Macs use `clang` by default, whereas the lab assumes `gcc`.

**Comment by ThrasherA** [comment]
Ah, I see. Thank you!
