### ISSUE TITLE
Question on Fractions

### ISSUE THREAD

**Issue by matthew-setiawan** [LangProc/langproc-2021-lab#17]
It's stated that "fraction consists of an optional leading - sign, a sequence of one or more decimal digits, a / sign, and another sequence of one or more decimal digits." 

By your definition, an input of 9/-3 should be considered as two separate integers which is 9 and -3, instead of a -3. Is this intended or is the intention is have 9/-3 be -3?

**Comment by ymherklotz** [comment]
> A fraction consists of an optional leading - sign, a sequence of one or more decimal digits, a / sign, and another sequence of one or more decimal digits.

Yeah exactly, as 9 is a valid decimal, it should be included.  Maybe test 16 can help clarify how fractions work by example.

**Comment by matthew-setiawan** [comment]
My flex works for 16 either way because there are no negatives in them. I wanted to know for the specific case when denominators are negative. Should we define fractions as [-]?[0-9]+[/][0-9]+ or [-]?[0-9]+[/]**[-]?**[0-9]+?

**Comment by johnwickerson** [comment]
The spec is accurate (in this instance, at least!), so you should follow it as it’s written.

**Comment by matthew-setiawan** [comment]
Alright, thanks!

**Comment by johnwickerson** [comment]
Hi @matthew-setiawan, if you're happy with this issue now, could you mark it as closed? Thanks.

**Comment by matthew-setiawan** [comment]
Sure. Thanks.
