### ISSUE TITLE
Printing whitespace at the beginning of outputs when I am not.

### ISSUE THREAD

**Issue by mahasch** [LangProc/langproc-2021-lab#19]
Im running this on VM and for some reason, even when I am not printing any whitespaces at the start, the stdout is showing that I do. 

(the _ is the whitespace )
__0.000
[a] 2
it's doing this instead of 
0.000
[a] 2

I'm not sure what the issue is.

**Comment by ymherklotz** [comment]
Hi, I'm guessing that this is your output for test 04.txt?

In that case, this is kind of expected with the default lexer, and requires a change to make it work properly.

Maybe this section from the spec can give a hint?

>  All other characters should not be counted (and should not appear in the output).

**Comment by ymherklotz** [comment]
Maybe running something like the following can give you a hint of what is going wrong:

``` shell
echo "... .    . . ..... /// /// ///// " | ./histogram
```

**Comment by ljc20** [comment]
I do understand what needs to be done by reading the flex file but I am confused by the syntax because whichever I try I get a compilation error

**Comment by ljc20** [comment]
It got resolved Thank you so much
