### ISSUE TITLE
Which extension to install in VSCode to use Flex?

### ISSUE THREAD

**Issue by mc1017** [LangProc/langproc-2021-lab#2]
Hi, may I ask which extension should I install in VSCode to use Flex?

**Comment by ALGCDG** [comment]
Hi, I don't have any particular recommendation for an extension, but I would suggest the best way to find one would be looking for a lex extension that also supports flex.

**Comment by ALGCDG** [comment]
Here is one: https://marketplace.visualstudio.com/items?itemName=faustinoaq.lex-flex-yacc-bison

**Comment by ptar124** [comment]
It says on my end that the extension has been unpublished?

**Comment by ALGCDG** [comment]
Here is an alternative: https://marketplace.visualstudio.com/items?itemName=luniclynx.lex

**Comment by sts219** [comment]
You can maybe try this one: https://marketplace.visualstudio.com/items?itemName=daohong-emilio.yash

**Comment by sts219** [comment]
Also if it doesn't seem to be working, check this
![InkedMicrosoftTeams-image_LI](https://user-images.githubusercontent.com/59866784/150554100-fc240171-9b1d-4a04-8d9a-fdb363dacc2d.jpg)
:
If it says plain text then click it and type in lex into the search bar, then select that and the syntax highlighting should start.

**Comment by mc1017** [comment]
Got it, thanks a lot!
