### ISSUE TITLE
8-bit characters

### ISSUE THREAD

**Issue by Cathy-DYX** [LangProc/langproc-2021-lab#22]
In the spec, it says that 'A word can also be any sequence of 8-bit characters beginning with [, and ending at the next ].'
I am not sure what exactly is a 8-bit character. Is it the same as what can be matched using a single dot '.'? Or does it specify a range of specific characters?

**Comment by ymherklotz** [comment]
Hi, yeah in the past there have been confusions, which is why this was specified. `.` should match all of those characters though, although you have to be careful about ending the word properly.

**Comment by Cathy-DYX** [comment]
Okay thank you!
