### ISSUE TITLE
Get fraction

### ISSUE THREAD

**Issue by Andyli-1020** [LangProc/langproc-2021-lab#23]
I am really struggling with the tests which contain fractions. It seems like my code can't convert fraction char into float properly.
![image](https://user-images.githubusercontent.com/72573344/151034875-0665ca8d-bb57-4630-809a-08e54c22631b.png)

**Comment by ymherklotz** [comment]
Hi, could you maybe give a description about what you are expecting, and what is actually happening? If it's a detailed question about your actual implementation, you can post a question in your Issue tracker of your personal repository as well.  However, if you can generalise the question it can help others too.

**Comment by Andyli-1020** [comment]
I am trying to get the fraction value of yytext and into yylval.numberValue. Thus, I define NUMBER as [-]?[0-9]*[/]?[0-9]*, but it doesn't work.
Like, the output of test 12 should be 0.500, but I get 1.000 instead.

![image](https://user-images.githubusercontent.com/72573344/151038261-bb1469c0-1ea8-4968-9dd5-9d9818659efb.png)
