### ISSUE TITLE
Can't print any words to *.stdout.txt

### ISSUE THREAD

**Issue by jlt20** [LangProc/langproc-2021-lab#24]
![Untitled](https://user-images.githubusercontent.com/72909581/151042050-99ebef44-403e-4022-ae80-58323dd6da83.png)

Hi, I can't seem to figure out how to print a word to the stdout.txt file. Can I get some pointers? Thank you!

**Comment by ymherklotz** [comment]
Hi, how are you running  the `histogram` program?

Using `test_lexer.sh`, anything printed to `std::cout` should go to the stdout.txt file.

**Comment by jlt20** [comment]
I’m using `make histogram` then `./test_lexer.sh` and the stout.txt file is empty.

**Comment by ymherklotz** [comment]
Could you attach the log of what 

./test_lexer.sh >test_lexer.log 2>&1

Produces in the `test_lexer.log` file? And could you also send all the outputs from your program for one of the test cases?

**Comment by jlt20** [comment]
[01.stderr.txt](https://github.com/LangProc/langproc-2021-lab/files/7941334/01.stderr.txt)
[01.diff.txt](https://git
[test_lexer.log](https://github.com/LangProc/langproc-2021-lab/files/7941339/test_lexer.log)
hub.com/LangProc/langproc-2021-lab/files/7941336/01.diff.txt)
github doesn't let me upload 01.stdout.txt cause it's an empty file.

**Comment by ymherklotz** [comment]
From `test_lexer.log` I can see that your program is segfaulting. Maybe #12 can help.

**Comment by jlt20** [comment]
hi, I've read through #12 and made some attempts but I still can't get rid of the segfault.
