### ISSUE TITLE
vagrant not set up properly

### ISSUE THREAD

**Issue by charlie-ccw** [LangProc/langproc-2021-lab#25]
when I run vagrant up and vagrant ssh, my machine didnt come with the required tools. it didnt recognised make as a command. when i copy and install the tools form the vagrant file, i can run "make" now, but the script is still throwing an error:

-bash: ./test_lexer.sh: /bin/bash^M: bad interpreter: No such file or directory

i also try destroy the VM machine and creating it again, but it still come with this error.

**Comment by ymherklotz** [comment]
So that error specifically is because there are windows line endings in the file.  I would recommend you set up your editor so that it preserves UNIX line endings, so that this doesn't happen.

To fix the line endings in the VM, you can also run: `dos2unix ./test_lexer.sh`.  Then `./test_lexer.sh` should work.

**Comment by charlie-ccw** [comment]
thx, the "./test_lexer.sh works" now, but i cannot see anything in the stdout.txt file for each single test. And every stderr.txt file says:
./test_lexer.sh: line 42: ./histogram: Permission denied
can u help me with it plz

**Comment by ymherklotz** [comment]
Hi, maybe the discussion in #11 can help? It seems to be the same issue maybe.

**Comment by charlie-ccw** [comment]
how to open the machine and copy those command line inside of it

**Comment by ymherklotz** [comment]
Just using the standard:

```
vagrant up
vagrant ssh
```

**Comment by charlie-ccw** [comment]
i tried wsl and it works now

**Comment by ymherklotz** [comment]
OK great, that should work well enough for the lab.
