### ISSUE TITLE
Different outputs when running exactly the same codes & effect of fprintf(stderr, …) on my output

### ISSUE THREAD

**Issue by VincentJue** [LangProc/langproc-2021-lab#27]
1. When I use ./test_lexer.sh to run exactly the same codes continuously, I often get different numbers of passes. Why is that?
2. I added fprintf(stderr, “Number stored : %f\n”, yylval.numberValue) and fprintf(stderr, “SUM : %f\n”, sum) in my cpp file to monitor the progression of the program. However when I delete these two sentences, my number of passes dropped by 2. I can’t see why they have effect on my actual output.

**Comment by ymherklotz** [comment]
1. I'm really not sure honestly, that shouldn't happen if there are no *segmentation faults* or weird memory errors.
2. That also shouldn't happen without weird memory errors. 

Make sure that you have no errors at all when you run the examples, and try to run the intermittently failing examples manually to see what happens.

**Comment by BPulmannova** [comment]
If your first couple of tests fail with a `Permission denied` message in *stderr.txt this could also come down to the syncing issue explored in #11.
