### ISSUE TITLE
Cannot SSH into Vagrant

### ISSUE THREAD

**Issue by dharmilshah99** [LangProc/langproc-2021-lab#3]
**Environment:**
OS: Windows 11
Vagrant Version: 2.2.16
Virtualbox Version: 6.1

**Issue**
I can't SSH into Vagrant as `vagrant up` times out and the VM seems to be stuck at the login screen. 

I also still cannot SSH into the VM after logging in with a username and password as "vagrant".

<img width="414" alt="image" src="https://user-images.githubusercontent.com/64415802/150546913-3d888af1-1f5b-453d-aee3-39f70ca5a880.png">

<img width="370" alt="image" src="https://user-images.githubusercontent.com/64415802/150546997-999d4cab-8cec-4354-b9c7-30bad9f0af50.png">

**Comment by petraratkai** [comment]
You may need to try commenting out some lines of your vagrantfile. Open vagrantfile in a text editor and try commenting out lines 27, 29 and 33.

**Comment by dharmilshah99** [comment]
> You may need to try uncommenting some lines of your vagrantfile. Open vagrantfile in a text editor and try uncommenting lines 27, 29 and 33.

This does not resolve the issue - `vagrant up` still times out and the VM is stuck at the login screen...

<img width="310" alt="image" src="https://user-images.githubusercontent.com/64415802/150548096-78666195-4d8f-459a-a921-c9c2194a2e7d.png">

<img width="392" alt="image" src="https://user-images.githubusercontent.com/64415802/150548640-5bd75c2f-abf2-419e-9075-be1d3cd52d62.png">

**Comment by ALGCDG** [comment]
Hi, are you using the git for windows terminal?

**Comment by ALGCDG** [comment]
In fact, if you are using windows, I would recommend using WSL with Ubuntu 16.04 (it should achieve the same result as the vm)

**Comment by ptar124** [comment]
I thought the environment for the labs should be in Ubuntu 20.04?

I'm also running WSL on Visual Studio Code, that should work right?

**Comment by ymherklotz** [comment]
It is Ubuntu 20.04, that's right.  WSL should be fine, but I would always at least check on Vagrant at the end, as it will be marked in vagrant.

**Comment by dharmilshah99** [comment]
> Hi, are you using the git for windows terminal?

Yes I am using git bash - I tried using command prompt but I am still facing the issue

**Comment by ymherklotz** [comment]
Yeah, last year using the GUI seemed to resolve it (even though you shouldn't use the GUI, and just use the git bash command line and type vagrant ssh).  For now, WSL should be good enought, and should basically be the same  environment.

**Comment by johnwickerson** [comment]
Hi @dharmilshah99, is this issue still causing you problems? If so, please provide further details. If not, please mark this issue as "closed".
