### ISSUE TITLE
histogram_type

### ISSUE THREAD

**Issue by huangweihan99** [LangProc/langproc-2021-lab#30]
Hi for the data type histogram_type with arguments of type std::string and unsigned, I get that the std::string should be yylval.wordValue, but what should the value of unsigned be? Is it just 1 to indicate that an instance of that particular word has been found? But if so how does the histogram increment the count for multiple instances of a particular word?

**Comment by ymherklotz** [comment]
In the comment above `histogram_type`, it says the following:

```
// Use a hash-table to maintain a word -> count mapping.
```

Does that help define what the `unsigned` should represent?  The incrementing logic is something that needs to be implemented when building the `histogram`.
