### ISSUE TITLE
Output formatting

### ISSUE THREAD

**Issue by huangweihan99** [LangProc/langproc-2021-lab#33]
![image](https://user-images.githubusercontent.com/83905363/151218601-f09e0875-4848-4b79-adfb-e43bb8ff17cf.png)

Hi, is there any reason why there is a < symbol before every entry? The 1,27d0 seems to indicate the number of entries too? I'm confused as I haven't added any extra printing instructions to the code.

**Comment by BPulmannova** [comment]
Hi, you are looking at the diff file showing you the difference between `test/ref/$BASENAME.stdout.txt` and `test/out/$BASENAME.stdout.txt` in a format produced by the [diff](https://linuxize.com/post/diff-command-in-linux/) command. If your output and the reference output are the same, this file should be empty.
