### ISSUE TITLE
Running test_lexer.sh

### ISSUE THREAD

**Issue by huangweihan99** [LangProc/langproc-2021-lab#34]
To test my lexer, I run vagrant up, vagrant ssh to run the VM and the correct environment (Ubuntu). However, when I enter the command ./test_lexer.sh, I get the following error:

-bash: ./test_lexer.sh: /bin/bash^M: bad interpreter: No such file or directory

![image](https://user-images.githubusercontent.com/83905363/151258119-d5da1d2f-7f3f-4450-b12a-68c88fa62886.png)

Is this an environment issue, if so how can I remedy it?

**Comment by ymherklotz** [comment]
I believe that #25 should help with that issue.

**Comment by huangweihan99** [comment]
![image](https://user-images.githubusercontent.com/83905363/151427950-0c045d20-688d-433a-968b-07b4b56845ba.png)
Hi I still get this following error message which is weird because I tried using dos2unix ./test_lexer.sh before and it worked in the morning.

dos2unix: ./test_lexer.sh: No such file or directory
dos2unix: Skipping ./test_lexer.sh, not a regular file.
