### ISSUE TITLE
Word within brackets

### ISSUE THREAD

**Issue by Aeroking21** [LangProc/langproc-2021-lab#35]
Hi,

I am confused about the definition of a word. 
1. I am not sure what it means by any sequence of 8-bit characters? 
2. Does it mean that it could include any sequence of chars as a char is only 1 byte?

`A word can also be any sequence of 8-bit characters beginning with [, and ending at the next ]. The word itself does not include the surrounding [ and ] characters. You can assume that such a sequence will never span a line-break.`

**Comment by ymherklotz** [comment]
Maybe #22 can help clarify the definition.
