### ISSUE TITLE
Char or String to Double conversion (precision)

### ISSUE THREAD

**Issue by LollyCraft** [LangProc/langproc-2021-lab#37]
In the instructions we are told the following:
`A decimal is a sequence of one or more decimal digits, preceded by an optional - sign, and optionally followed by a . sign and zero or more decimal digits. **It should be interpreted as a decimal double-precision number.**`

So, when considering the precision, should we assume that the conversion of a number with more decimal digits
-  is fit into a double with max nr of decimals, or 
- is rounded up or rounded down to the needed double-precision?

So for example, if we have the following char * signifing a number as an edge case:
`1.11199776575`
Would this be converted to 1.111998 or 1.111 or 1.112 in order to be added to the total sum?
- In the case that we convert the number to its full double value (has max nr of decimals)(1.111998), then the final sum will be affected by the lower decimals, which could lead to a discrepancy in the result.
- In the case that we consider 1.111, then we could lose data as the rounding it down is not appropiate, but keep double-precision.
- In the case that we take 1.112, then we would have the double precision needed, and a rounding up has been done.

**Comment by ymherklotz** [comment]
I think the spec is quite clear on this:

> It should be interpreted as a decimal double-precision number.

You should store the lexed decimal as a double.

> This should be printed in decimal, and include exactly three fractional digits.

The result should be printed with three fractional digits, i.e. precision doesn't play a factor until the printing.

**Comment by LollyCraft** [comment]
Alright, thanks for the clarification.
