### ISSUE TITLE
No private repository link for langproc-2021-lab

### ISSUE THREAD

**Issue by VincentJue** [LangProc/langproc-2021-lab#39]
![screenshot](https://user-images.githubusercontent.com/97638517/151470444-c068b913-074a-4de8-a2f3-5be28cb1cc75.png)

**Comment by VincentJue** [comment]
Also I'm not quite sure how to do the "Setting up your git repository" part.
![image](https://user-images.githubusercontent.com/97638517/151471481-07b03c13-a01d-4875-9f09-cf9d0c375f05.png)

**Comment by johnwickerson** [comment]
Hi Vincent, it's because you haven't accepted the invitation that was sent to the email address associated with your github username "VincentJue". It may have gone into a junk folder. That's why you can't see the repo (yet). I've re-sent the invitation in case it makes it easier for you to find.
