### ISSUE TITLE
Vagrant not running 

### ISSUE THREAD

**Issue by Aeroking21** [LangProc/langproc-2021-lab#4]
I managed to get vagrant running and I then exited and tried to run it again using vagrant up but it now says

==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

**Comment by ymherklotz** [comment]
Yeah, that's completely normal. It's because it was never stopped.  You can just run `vagrant ssh` again, and it should work.

To turn off the VM, you can run `vagrant halt`, after which you need to run `vagrant up` again.

**Comment by ymherklotz** [comment]
The note about provisioning is not an error, it's just a note.  You don't want to provision the VM again, so you can ignore it.
