### ISSUE TITLE
Are we allowed to add a new TokenValue and TokenType?

### ISSUE THREAD

**Issue by J-u1i0** [LangProc/langproc-2021-lab#40]

**Comment by IBricchi** [comment]
I don't think there's any reason to add a new token type or value. What exactly are you trying to add?

**Comment by J-u1i0** [comment]
On second thought, I would only need to add a new token type.
I am adding a new token type for the fractions. This would mean that I store the fraction string in the wordValue space of the union and can recognize this is a fraction because I would be returning a Fraction token which would mean that I can do substrings in C++ to obtain the denominator and numerator of the fraction.
The reason I am doing this is that I am not very familiar with C so I am taking the fraction string over to the C++ realm.

**Comment by J-u1i0** [comment]
I have already implemented this solution and it works.

**Comment by ymherklotz** [comment]
I would say it is probably allowed, but it's definitely not necessary. Maybe @johnwickerson can clarify.

**Comment by J-u1i0** [comment]
Should I email him?

**Comment by johnwickerson** [comment]
Yeah this should be ok. As @ymherklotz says, it involves more changes to the codebase than are strictly necessary, but I doubt it'll break anything.

**Comment by J-u1i0** [comment]
Ok, thank you.
But how would I do substring in C, to select the numerator and denominator?

**Comment by ymherklotz** [comment]
You aren't limited to C in the flex file, because eventually it gets compiled in C++, so you can use your normal code in the flex file too.

**Comment by J-u1i0** [comment]
Ohh, ok thank you very much!
