### ISSUE TITLE
Adding our own test cases

### ISSUE THREAD

**Issue by vaclavpavlicek** [LangProc/langproc-2021-lab#41]
Hello, is it OK to commit and submit our own input files with expected reference files? Or should I remove them from the final submission? I would like to add more testing inputs starting with index 25.

**Comment by johnwickerson** [comment]
I think that should be fine. There's no point including them because I'll ignore any additional test cases and you won't get any additional credit, but there shouldn't be any problem.

**Comment by vaclavpavlicek** [comment]
Ok thanks, I would like to include them so everything is properly synced on GitHub. I don't feel that ignoring them in .gitignore is a good solution.
