### ISSUE TITLE
No output showing, but passing tests.

### ISSUE THREAD

**Issue by harshil-shah9900** [LangProc/langproc-2021-lab#42]
I'm not seeing any output when manually running ./histogram and inputting something, but I seem to pass the tests. I used to see the output, but after some changes to the lexer I no longer. Is this ok if I still pass the tests?

**Comment by petraratkai** [comment]
How exactly are you providing the input? Please give some more details.

**Comment by harshil-shah9900** [comment]
I run "make histogram" to get the histogram output file. I run it, ./histogram, and it waits for input. If I type in something like "a abc 12 3"  then press enter, I receive no output and the cursor just resets to the start of the new line.

**Comment by ymherklotz** [comment]
You need to "end the file" manually when using the command line.  You can do this by pressing: `CTRL + D`.

Otherwise, you can also run inputs through your histogram program manually by using:

```shell
echo "a" | ./histogram
```

**Comment by harshil-shah9900** [comment]
Thanks!
