### ISSUE TITLE
Testing on Vagrant

### ISSUE THREAD

**Issue by huangweihan99** [LangProc/langproc-2021-lab#43]
Hi, I did everything using WSL and I was wondering how to check whether my code runs on the Vagrant environment too?

**Comment by IBricchi** [comment]
You should be able to just clone a copy of your repo to your vagrant virtual machine and test it there. Just follow the instructions for setting up vagrant from the lab instructions.

**Comment by petraratkai** [comment]
Well the best was is to run Vagrant if you have it set up. If that's not an option then if your WSL uses Ubuntu 20.04 then it should be the same environment as Vagrant, so it would work on Vagrant too.

**Comment by huangweihan99** [comment]
Hi, I've tried running tests on both WSL and Vagrant, I pass all on WSL, but only 1 on vagrant

**Comment by petraratkai** [comment]
Are you sure you're running the same code on both? Also what version of WSL are you running?

**Comment by huangweihan99** [comment]
Sry how do I check the version of WSL? I'm not quite sure how to display my code on vagrant too..

![image](https://user-images.githubusercontent.com/83905363/151561754-21b81889-2650-4e90-bf68-240555eae4f9.png)

**Comment by huangweihan99** [comment]
Sry I just checked I'm using WSL 2

**Comment by petraratkai** [comment]
Sorry, I meant what version of Ubuntu are you using? Just run lsb_release -a to see if you don't know.

**Comment by huangweihan99** [comment]
I'm using 20.04

**Comment by petraratkai** [comment]
Okay then how exactly are you running the script on vagrant and in WSL? Are you sure the code is the same in wsl and in vagrant?

**Comment by huangweihan99** [comment]
I'm not quite sure how to check my code in vagrant. I'm just running vagrant in my command prompt and running wsl via VSCode

**Comment by petraratkai** [comment]
Are you in the same folder for both when you're running it?

**Comment by huangweihan99** [comment]
![image](https://user-images.githubusercontent.com/83905363/151563654-2b31f20e-44fa-4308-9793-0ab5d30337b6.png)

This is my path on WSL, shouldn't the directories be synced, I've tried creating random files on the WSL version and the changes are reflected.

**Comment by ymherklotz** [comment]
Hmm, they should be synced. Maybe try pushing your changes from WSL to Github, then try git pull in the directory in vagrant.  I can't really think of another reason why they differ so greatly.  If it still doesn't work, then maybe can you post the outputs of

```
git log -1
```

In both WSL and Vagrant.

**Comment by huangweihan99** [comment]
WSL:

![image](https://user-images.githubusercontent.com/83905363/151574291-fdb43133-4801-428c-80bc-7bebab074225.png)

Vagrant:

![image](https://user-images.githubusercontent.com/83905363/151574344-d95f5f5c-1542-4770-b7ec-e5717e62ed04.png)

**Comment by ymherklotz** [comment]
And what do the stderr, stdout and diff files look like in the faiures?

**Comment by huangweihan99** [comment]
I fail test 1 and these are the outputs:

![image](https://user-images.githubusercontent.com/83905363/151576103-7fe417a9-5bdc-45cf-a3d8-a3d941f0b307.png)

**Comment by ymherklotz** [comment]
Well that seems like it passed it..

Can you try running the following command in vagrant and trying again?

```shell
find . -path ./misc -prune -o -exec dos2unix {} \;
```

**Comment by huangweihan99** [comment]
Hi it passes 14/24 now (fails the first 10), but it's still short of the 24 I've passed in WSL. The stderr, stdout and diff files for one of the failed test is:

![image](https://user-images.githubusercontent.com/83905363/151578048-fc234546-b525-47bf-9269-662c9402c15b.png)

**Comment by ymherklotz** [comment]
Ah, that I now know the solution to: #11 should fix this.

**Comment by huangweihan99** [comment]
Thank you so much for your help! All the tests pass on vagrant now :)
