### ISSUE TITLE
bin/eval_expr: binding format

### ISSUE THREAD

**Issue by vaclavpavlicek** [LangProc/langproc-2021-lab#45]
Hello, I am trying to finish `TODO-B` in lab 2. I ran the following commands to build the executables.

```
make clean
make bin/print_canonical bin/eval_expr -B
```

Then I ran

```
vagrant@ubuntu-focal:/vagrant/2-parsers$ bin/eval_expr
x 1
Parse error : syntax error
```

and I got the syntax error. Why is that? Is this the wrong format for binding? I took a look at the input file `valid_expressions.input.txt` and it contains binding of the form `x 2 y 3`. Could you please tell me what is from with my binding inputted to the `bin/eval_expr`?

**Comment by ymherklotz** [comment]
Yes, bindings are passed on the command line as arguments to eval_expr.  So more something like:

```
./bin/eval_expr x 1
```

You can have a look into the main function to see how it works.

**Comment by vaclavpavlicek** [comment]
I see, thanks!
