### ISSUE TITLE
Wrong order on [] and [ ] for test case 17

### ISSUE THREAD

**Issue by JoachimLar** [LangProc/langproc-2021-lab#47]
When I run test case 17 the following output:

Word : []
Newline
Word : [ ]
Newline
Word : [1/5]
Newline
0.000
[ ] 1
[1/5] 1
[] 1

It seems like it is in the correct order when it reads everything but after it goes through the sorting function the order changes. Any ideas what could cause this? The other 16 test cases work fine

**Comment by ymherklotz** [comment]
Well the sorting function will sort everything properly, so that everything is printed in the right order.  This doesn't mean it will be the same order as the lexing.  However, you shouldn't have to modify anyhting with the sorting, are you sure you are printing out the words in the loop after it's sorted?

**Comment by JoachimLar** [comment]
Yes I print it out right after these lines:
 while(it!=sorted.end()){
        std::string name=it->first;
        unsigned count=it->second;
        // TODO: Print out `name` and `count` to std::cout

Also, I should say, the brackets are included in the name when I print them. For outputs that don't include brackets (ex [a-z]), I add them once I do the print in the main file. But that should still work, right?

**Comment by ymherklotz** [comment]
Ah ok, I think that's why it might be going wrong, you always want to strip the brackets when you lex, because the word itself doesn't include the brackets.

**Comment by JoachimLar** [comment]
Ah okay, that makes sense. 
I modified it as you described and it works fine now. Thank you!
