### ISSUE TITLE
Parse file are we allowed to change the lexer flex

### ISSUE THREAD

**Issue by JamesOngICL** [LangProc/langproc-2021-lab#48]
[*]             { return T_TIMES; }
[+]             { return T_PLUS; }
[\^]            { return T_EXPONENT; }
[-]             { return T_MINUS; }

[(]             { return T_LBRACKET; }
[)]             { return T_RBRACKET; }

log             { return T_LOG; }
exp             { return T_EXP; }

Hi sir, this is part of the lexer flex file for implementing parsers. However, it appears that this is an incomprehensive list of tokens. I want to ask if we can modify this flex file to include more tokens such as divide. Thank you.

**Comment by Fiwo735** [comment]
I would say that's fine, but @johnwickerson can confirm it for sure

**Comment by johnwickerson** [comment]
Fine by me too.
