### ISSUE TITLE
[Lab 1] Cannot run Testing Script

### ISSUE THREAD

**Issue by dharmilshah99** [LangProc/langproc-2021-lab#5]
**Environment:**
- Ubuntu 20.04 in WSL2

**Issue**
- I cannot run `./test_lexer.sh` even after adding unix execute permissions. I tried to resolve this by first running dos2unix on the script.
- However, when I look at some of the `stdout`s in the `test` folder after running the script,  some stuff is being printed despite there being no print statements in `histogram_main.cpp`. I have not modified anything yet.
- Is this expected?

<img width="281" alt="image" src="https://user-images.githubusercontent.com/64415802/150551863-153743b6-de65-4a08-8186-a8574876c1ce.png">

**Comment by ymherklotz** [comment]
Hi, could you print the errors that you get when running ./test_lexer.sh?

**Comment by dharmilshah99** [comment]
> Hi, could you print the errors that you get when running ./test_lexer.sh?

<img width="592" alt="image" src="https://user-images.githubusercontent.com/64415802/150552328-99fa41f7-f248-420d-ba52-0b1e40a48bdd.png">
<img width="261" alt="image" src="https://user-images.githubusercontent.com/64415802/150552366-63dea9ae-5626-49a4-adbf-bca1b6e1657e.png">

**Comment by ymherklotz** [comment]
Yeah, that seems to be running fine.  The printing is normal too, you now need to work on implementing the spec for the lab.  The printing is most likely coming from unparsed constructs from the lex file.

**Comment by johnwickerson** [comment]
Hi @dharmilshah99, is this issue still causing you problems? If so, please provide further details. If not, please mark this issue as "closed".
