### ISSUE TITLE
C++ Version

### ISSUE THREAD

**Issue by Nikhil-Narayanan** [LangProc/langproc-2021-lab#50]
Hi what version of C++ does the lab use? I wanted to use the contains function in string but it only exists for C++ 23 and onwards?

**Comment by ymherklotz** [comment]
Hi, by default the lab uses C++03 or C++11 I think. However, you can check what compiler version is installed in the ubuntu machine, and check what the highest standard is that is supported by the compiler. I would guess that is C++17, so c++23 seems a bit too advanced, but it could work.

**Comment by Nikhil-Narayanan** [comment]
Should I assume C++11 then?

**Comment by ymherklotz** [comment]
Well you could change the Makefile I think and use C++17 or later.  That's definitely possible for the Compiler.  However, the labs should not really require any newer features, so I would probably recommend with sticking with C++11.

**Comment by Nikhil-Narayanan** [comment]
Sounds good, thank you!
