### ISSUE TITLE
Test 17 issue, word within brackets

### ISSUE THREAD

**Issue by bakhtiarZ** [LangProc/langproc-2021-lab#51]
Hi,

I am struggling to "splice" the value I receive so that what goes into the histogram is not [x] but x instead. I am having issues because yytext is not an std::string so i cannot use substr. 

I want to create a new cstring or something that is yytext but with the first and last characters eliminated. I can then just use this for the cpp main. 

I tried this : 
std::string tmp = "";
for(int i = 1; i<strlen(yytext); i++){ 
tmp.push_back(yytext[i]); 
}
yy.wordValue = new tmp;

But it doesn't work. I am also having issues trying to debug this because I cannot seem to be able to fprintf a std::string type.

**Comment by BPulmannova** [comment]
Hi,
> yytext is not an std::string so i cannot use substr

One way to get around this could be to [construct](https://www.cplusplus.com/reference/string/string/string/) a string out of yytext and process that.
> I cannot seem to be able to fprintf a std::string type

To fprintf std::string for debug purposes you can convert it to a C-style string (print `my_string.c_str()` instead of `my_string`).

**Comment by bakhtiarZ** [comment]
thanks
