### ISSUE TITLE
[a-zA-Z]+ accepting [[] and [] as a word? 

### ISSUE THREAD

**Issue by souramam1** [LangProc/langproc-2021-lab#53]
I'm having an issue where the regex [a-zA-Z]+ is accepting [] as a word and [[] which is causing problems for matching actual words within brackets. I've researched a lot online and it doesn't make mention that this should be happening. What could be the problem?

**Comment by johnwickerson** [comment]
Hm, I don’t see why that regex would match brackets. It clearly says to match non-empty sequences of alphabetic characters! Something else must be happening.
