### ISSUE TITLE
Question about what are we allowed to edit in the parser lab 2

### ISSUE THREAD

**Issue by matthew-setiawan** [LangProc/langproc-2021-lab#54]
Are we allowed to edit all the files? Specifically, asides from the provided types and tokens,

`%token T_TIMES T_DIVIDE T_PLUS T_MINUS T_EXPONENT
%token T_LBRACKET T_RBRACKET
%token T_LOG T_EXP T_SQRT
%token T_NUMBER T_VARIABLE

%type <expr> EXPR TERM UNARY FACTOR
%type <number> T_NUMBER
%type <string> T_VARIABLE T_LOG T_EXP T_SQRT FUNCTION_NAME`

Can we add more to our liking?

**Comment by johnwickerson** [comment]
I think this might be a duplicate of https://github.com/LangProc/langproc-2021-lab/issues/48

**Comment by matthew-setiawan** [comment]
Got it, thanks.
