### ISSUE TITLE
Fraction with negative denominator

### ISSUE THREAD

**Issue by vaclavpavlicek** [LangProc/langproc-2021-lab#55]
Hello, is it possible to have a negative denominator in the fraction? For example like this: `1/-2`. Should this be lexed as `-0.500` or `1-2=-1`? According to the specifications, I think that it should be `1-2=-1`, but I would like to double-check before the final submission.

**Comment by johnwickerson** [comment]
Possible duplicate of https://github.com/LangProc/langproc-2021-lab/issues/17

**Comment by vaclavpavlicek** [comment]
Makes sense now.  Thank you!
