### ISSUE TITLE
Personal test cases for lab1

### ISSUE THREAD

**Issue by bakhtiarZ** [LangProc/langproc-2021-lab#57]
Hi,

I noticed all the test inputs have a newline at the end, should we assume this is going to be the case for all input tests?

And should we create our own testing following this format?

I haven't yet investigated why but the automated testing results in a fail if there is no Newline at the end of our input.

**Comment by bakhtiarZ** [comment]
And are we to remove this extra testing prior to submitting the file?

**Comment by ymherklotz** [comment]
Hi, maybe #41 is relevant.  About the line endings, It's quite standard that files should have end lines in linux (seems to be required for POSIX compliance).  For example, if you count the lines of a file using `wc`, then it won't count the last line if it doesn't have a newline, so you actually will get a line count of 1 less than what it should be.

**Comment by bakhtiarZ** [comment]
Thank you
