### ISSUE TITLE
Undefined reference to yylex()

### ISSUE THREAD

**Issue by lucianecchi** [LangProc/langproc-2021-lab#58]
Hi, when I try and run` make histogram `(from the vagrant) I get the following error: /vagrant/1-regexes/histogram_main.cpp:28: undefined reference to `yylex()'.

I have tried downgrading flex to flex old and adding "C" to the external declaration of yylex() but I have had no success. 

Any idea on what I could do?

**Comment by ymherklotz** [comment]
Hi, could you show the whole log of what 

```
make clean
make -B
```

prints?

**Comment by lucianecchi** [comment]
vagrant@ubuntu-focal:/vagrant/1-regexes$ make clean 
rm -f histogram histogram.exe
rm -f *.yy.cpp
rm -f test/out/*
vagrant@ubuntu-focal:/vagrant/1-regexes$ make -B
flex -o histogram_lexer.yy.cpp  histogram_lexer.flex
/usr/bin/m4:stdin:1356: ERROR: end of file in string
make: *** [makefile:12: histogram_lexer.yy.cpp] Error 1

**Comment by lucianecchi** [comment]
and if I try to run make histogram without cleaning (so `make clean` `make histogram` `make histogram` in sequence) the error it gives for the second make histogram is 

g++ -W -Wall -g  -std=c++0x -Wno-unused-function -o histogram  histogram_lexer.yy.o histogram_main.o
histogram_main.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
make: *** [makefile:15: histogram] Error 1

plus a bunch of warnings
