### ISSUE TITLE
Something in stdout even when all std::cout are commented out.

### ISSUE THREAD

**Issue by ptar124** [LangProc/langproc-2021-lab#59]
As the topic says, there seems to be something in stdout. On case 3, it's merely a single space, but on some there were tab characters and especially on case 21, there's a monstrously huge paragraph of special characters that I can only assume are remnants of html tags. Every single std::cout is commented out, I've searched through every single one of it.

![image](https://user-images.githubusercontent.com/22909681/151717654-fb10fceb-b8b3-4ed8-9230-343196d12d90.png)

**Comment by ptar124** [comment]
on further inspection it looks like the program just throws whatever it thinks is invalid into stdout, which is extremely weird to me

**Comment by ptar124** [comment]
I've resolved this. I added #include <iostream> onto the top of the histogram_main.cpp which made it do the funny things that it did.

**Comment by BPulmannova** [comment]
I think #12 and #19 might be relevant

**Comment by ptar124** [comment]
I've read both issues; I still wasn't able to figure out what section needs to be changed.

**Comment by ymherklotz** [comment]
I think especially #19 explains what needs to be changed.  However, if you have more specific questions about that you can ask.
