### ISSUE TITLE
decimal

### ISSUE THREAD

**Issue by bardia01** [LangProc/langproc-2021-lab#62]
Hi, in the spec this part is unclear :
"A decimal is a sequence of one or more decimal digits, preceded by an optional - sign, and optionally followed by a . sign and zero or more decimal digits. It should be interpreted as a decimal double-precision number."

does this mean something like "5." is allowed? Since this is one decimal digit followed by a "." and zero more decimal digits

**Comment by johnwickerson** [comment]
Which bit do you find unclear?

**Comment by bardia01** [comment]
Hi, specifically this bit "and optionally followed by a . sign and zero or more decimal digits".

Could you have a decimal digit followed by a . sign and nothing else?

Sorry for not specifying in the original post.

**Comment by johnwickerson** [comment]
I think the spec already answers your question, no?

**Comment by bardia01** [comment]
I would say that based from the spec that something like "5." is allowed, but how would I add this to the sum? Would this just be 5.0?

**Comment by johnwickerson** [comment]
Exactly

**Comment by bardia01** [comment]
Hi sir, just as a follow-up for my own curiosity, allowing "5." is the same as allowing only "5" and then not parsing/sending or through the full stop since for the sum, "5" and "5." hold the same value?

**Comment by johnwickerson** [comment]
Yes, that seems reasonable. I would just be careful to make sure that you do actually _consume_ the “.”, even if you don’t do anything with it, because you don’t want to leave that around and accidentally re-lex it as part of the _next_ token!

**Comment by bardia01** [comment]
Okay sounds good, thanks sir
