### ISSUE TITLE
When to use \ to escape operators in square brackets?

### ISSUE THREAD

**Issue by dharmilshah99** [LangProc/langproc-2021-lab#64]
The `.` operator doesn't seem to need escaping in `[.]` if we just want to match `.`.

What operators are treated as regular characters in square brackets? Is there any documentation for this?

**Comment by ymherklotz** [comment]
There is quite good documentation of `flex` in their man page:

```shell
man 1 flex
```

Or you can also see it here: http://dinosaur.compilertools.net/flex/manpage.html

It says the following:

> Note that inside of a character class, all regular expression operators lose their special  meaning  except  escape ('\') and the character class operators, '-', ']', and, at the beginning of the class, '^'.

**Comment by dharmilshah99** [comment]
This was really helpful. Thanks!
