### ISSUE TITLE
submission

### ISSUE THREAD

**Issue by xy2120** [LangProc/langproc-2021-lab#66]
Hi
I accidently created a new branch in the private lab program and submitted all the files to that new branch called master.
I try to submit again to the main branch but it kept saying fail to push.
I was thinking it it possible if I just leave it there in the new branch or can I manully upload the files to the main branch?

**Comment by ymherklotz** [comment]
Leaving them in the branch is fine.  However, you should be able to push to the main branch as well.

```shell
git push origin <local-branch-name>:<remote-branch-name>
```

So in this case it might be something like:

```shell
git push origin master:main
```

But you should check what your repo looks like locally and adapt that to the command above.  However, as long as you push the commit you have locally, it should be fine.

**Comment by xy2120** [comment]
Thanks
