### ISSUE TITLE
Headers not working

### ISSUE THREAD

**Issue by JosiahBegley720** [LangProc/langproc-2021-lab#67]
#include <unistd.h> (in histogram_lexer.yy.cpp)
#ifndef histogram_hpp (in histogram.hpp)

are not recognized by wsl

**Comment by ymherklotz** [comment]
Not sure why these are not recognised, however, it should all work in the lab environment (`vagrant`). Maybe check you have installed all necessary dependencies.

**Comment by JosiahBegley720** [comment]
i am operating in vagrant, and have installed al the correct dependencies to my knowledge. `#include <unistd.h>` still causes an error

**Comment by ymherklotz** [comment]
Have you written `#include <unistd.h>` anywhere?
