### ISSUE TITLE
histogram: permission denied

### ISSUE THREAD

**Issue by JosiahBegley720** [LangProc/langproc-2021-lab#68]
./test_lexer.sh: line 41: ./histogram: Permission denied
in stderr.txt

**Comment by johnwickerson** [comment]
You could try a `chmod +x histogram`, to make sure that the histogram program is actually e`x`ecutable.

**Comment by JosiahBegley720** [comment]
i have tried that

**Comment by JosiahBegley720** [comment]
my return value is '0: command not found'. which suggests the operation was not successful as well as the fast the sterr remains the same

**Comment by JosiahBegley720** [comment]
It could be due to the fact that `#include <unistd.h>`  is errored in `histogram_lexer.yy.cpp `
which results in ` histogram.hpp ` not correclty producing an executable `histogram` file. But this package should been downloaded when i set up the environment

**Comment by JosiahBegley720** [comment]
no matter what i have done, the header #include<unistd.h> is causing an error. I believe i have installed the correct environment and packages

**Comment by JosiahBegley720** [comment]
> You could try a `chmod +x histogram`, to make sure that the histogram program is actually e`x`ecutable.
i have tried that
my return value is '0: command not found'. which suggests the operation was not successful as well as the fact that sterr remains the same
It could be due to the fact that #include <unistd.h> is errored in histogram_lexer.yy.cpp
which results in histogram.hpp not correclty producing an executable histogram file. But this package should been downloaded when i set up the environment. I have the text editor open in windows, so i was assuming it was just errored in the windows environment due to it being a linux package, so i have ignored it up to this point as the package should have been installed in my VM environemt
no matter what i have done, the header #include<unistd.h> is causing an error. I believe i have installed the correct environment and packages

**Comment by ymherklotz** [comment]
Make sure that you are using vagrant. Then, about the `Permission denied` issue, you can check #11 which might provide a work around.
