### ISSUE TITLE
LAB 2： Permission denied

### ISSUE THREAD

**Issue by charlie-ccw** [LangProc/langproc-2021-lab#69]
Hi I tried to test the Lab 2: Parsers, and some of the tests come with Error and show me this:

./test_parser.sh: line 56: bin/eval_expr: Permission denied

I did tried the mothed in #11 but it is only useful to Lab 1 and will send me to the lab 1 file direction. can u give some new command lines that I can type into Ubuntu to run lab2 properly?

**Comment by ymherklotz** [comment]
Hi, maybe you can have a look at the commands and see how to go to the lab 2 directory?

**Comment by charlie-ccw** [comment]
Hi, I tried, and then none of the tests passes. However, it passed 27 tests and the remainder shows the error of 'permission denied' before I tried.

**Comment by ymherklotz** [comment]
After you run the tests, what does the following command print?

```
pwd
```

**Comment by charlie-ccw** [comment]
/vagrant/2-parsers

**Comment by ymherklotz** [comment]
Does that give you a hint as to why it isn't working? Which one of the four commands do you think failed?

If you want a long description of what a command does, you can use:

```
man <command>
```

for example:

```
man ls
```

**Comment by charlie-ccw** [comment]
I changed the command lines to be like these:
cp -r /vagrant ~/langproc
cd ~/langproc/2-*
chmod +x test_parsers.sh
./test_parsers.sh

After I typed these four lines, the terminal shows this:
-bash: ./test_parsers.sh: No such file or directory

then, i typed ' ls ' and see these:
bin  include  makefile  readme.md  src  test  test_parser.sh

can u check that is there any error in my command lines or what should i do next?

**Comment by ymherklotz** [comment]
Ah, I think it's `test_parser.sh`, instead of `test_parsers.sh`

**Comment by charlie-ccw** [comment]
it shows 0 pass,  However, it passed 27 tests and the remainder shows the error of 'permission denied' before I tried.

**Comment by charlie-ccw** [comment]
also, when i use wsl to test these, it shows 54 passes

**Comment by ymherklotz** [comment]
Are you sure that your current working directory is in `~/langproc/2-parsers`? and not in `/vagrant/2-parsers`? Could you send the whole log of the test_parser.sh run?

```
pwd >test_parser.log
./test_parser.sh >>test_parser.log 2>&1
```

And then send me the `test_parser.log` file?

**Comment by Strikewind** [comment]
![image](https://user-images.githubusercontent.com/93332879/152606195-cefbfc01-7ab2-4cd1-966f-6fdf1f3d0895.png)
Adding this to the Vagrantfile allows all made files to have execute permissions
```
config.vm.synced_folder ".", "/vagrant",
    mount_options: ["dmode=775,fmode=777"]
```

**Comment by ymherklotz** [comment]
Oh wow, that is quite extreme, but fair enough if that works.  Something like that shouldn't be necessary, it's really an issue with windows interferring with permissions it shouldn't touch.

**Comment by charlie-ccw** [comment]
thx so much, it works perfectly.
