### ISSUE TITLE
Syncing of files between VM and local machine

### ISSUE THREAD

**Issue by huangweihan99** [LangProc/langproc-2021-lab#7]
I've clones the repo twice, once in my local machine to get the vagrant up and another time in the VM. However, I'm not sure of how to sync my files on the VM to my local machine and vice versa. I've tried making changes to the repo on my local machine but the changes aren't reflected in the repo on the VM. I think I'm confused about the whole configuration of the environment, could I get some clarification on how to sync my files?

**Comment by petraratkai** [comment]
you should make the changes in your VM because that's where you should test your code. You don't need to worry about the files on the local machine, just make sure that when you push to Git, you push from the repo on the VM

**Comment by huangweihan99** [comment]
I don't know how to make the changes in my VM though, do I login to ubuntu using my virtual box, or do I do everything from my command prompt? I can't seem to use the command code . to open the repo in VSCode from my CM.

**Comment by petraratkai** [comment]
I'm not sure how you can set up VSCode from the vagrant terminal, but you can always just open the files in a text editor on your local machine because these files should be shared between the vm and your local machine. And then you can use the vagrant commandline to run your code.

**Comment by huangweihan99** [comment]
Where do I find the files from the VM on my local machine?

**Comment by sts219** [comment]
Usually they'll be in the same folder you ran `vagrant up` from

**Comment by ymherklotz** [comment]
If you use `vagrant`, then it will sync the folder from your host machine with the `/vagrant` folder on the VM.  So if you edit files on your host machine, they will also change in the VM.

**Comment by huangweihan99** [comment]
I've tried creating a new file in the repo on my host machine, but it isn't reflected in the VM

**Comment by huangweihan99** [comment]
![image](https://user-images.githubusercontent.com/83905363/150561195-01ba2cec-a633-43de-83ba-2d81f5fe1d81.png)
![image](https://user-images.githubusercontent.com/83905363/150561332-3ce12b05-a638-494d-a0e6-3faa66e73981.png)

I created a new file test.txt on my host machine, but it isn't in the VM

**Comment by ymherklotz** [comment]
Ah, if you are using vagrant, cloning it twice is unnecessary, as it should be
synced into the VM.

When you are in the VM, you should find all your files by doing:

```
cd /vagrant
ls
```

**Comment by huangweihan99** [comment]
![image](https://user-images.githubusercontent.com/83905363/150563375-c4f403b3-3227-4bca-b131-2452eb76d4d8.png)
I got this when I type in cd /vagrant and was told by the TAs that it was because I was alrdy in /vagrant. However, the repo wasn't in there, so I was told to clone it again. Should I delete the repo from the VM, if so what command do I use?

**Comment by huangweihan99** [comment]
![image](https://user-images.githubusercontent.com/83905363/150563819-eb9daa6b-9df1-4ceb-9f1f-0d27b93d035d.png)
I've deleted it but I just can't seem to find the file /vagrant

**Comment by ymherklotz** [comment]
Hmm, you may have to try and restart the VM then, that seems to happen somehow if there were errors when it was setting up.

First, exit the VM using: `exit`.
Then you can reset it using the following:

```
vagrant destroy
vagrant up
vagrant ssh
cd /vagrant
```

**Comment by huangweihan99** [comment]
![image](https://user-images.githubusercontent.com/83905363/150565115-9ce95919-dc15-41d1-8255-76b60f4c533e.png)

Oooh ok thank you so much that worked!

**Comment by ymherklotz** [comment]
OK, just to correct myself: `vagrant destroy` completely deletes the VM, so only do that if something is wrong. Glad that worked though.

**Comment by huangweihan99** [comment]
I actually didn't use the vagrant destroy command, all I did was delete the repo cloned into the VM and then exit before relaunching it and that seemed to work. Thank you so much for your help.

**Comment by bakhtiarZ** [comment]
Hi just to add onto this,

I can't seem to get it to sync although within my "Synced folders" file in the vm it has:

{"virtualbox":{"/vagrant":{"guestpath":"/vagrant","hostpath":"C:/Users/bakht/langproc-2021-lab-bm920","disabled":false,"__vagrantfile":true}}}

Is this the correct thing? It looks like this could be why my folders arent synced.

**Comment by ymherklotz** [comment]
> {"virtualbox":{"/vagrant":{"guestpath":"/vagrant","hostpath":"C:/Users/bakht/langproc-2021-lab-bm920","disabled":false,"__vagrantfile":true}}}

Hmm, I'm not sure where you got this from, but it does indeed seem correct.  If
have done:

    vagrant destroy
    vagrant up
    vagrant ssh

and the `/vagrant` folder is still empty, then something went wrong.  If that is
the case, and you are using windows, it might be easier to do the lab using WSL,
at least until we can maybe debug this further.
