### ISSUE TITLE
Make clean not removing all files

### ISSUE THREAD

**Issue by Nikhil-Narayanan** [LangProc/langproc-2021-lab#70]
I've needed to add the following line to the makefile to properly clean it before submission in lab1:
rm -f histogram histogram.exe histogram_main.o histogram_lexer.yy.o
And I've needed to add lines in lab 2:
rm src/maths_parser.output
rm src/maths_parser.tab.hpp

Should this be changed everywhere?

**Comment by ymherklotz** [comment]
Yeah that's definitely something that could be added to the `makefile`, thanks! I can change it later, or if you feel comfortable with `git` you could even try to submit a pull-request.

**Comment by Nikhil-Narayanan** [comment]
Hi, I just made a PR

**Comment by Nikhil-Narayanan** [comment]
I just saw that it's possible to link the pull request to the issue, so I'll keep it open until its merged just to try using that feature in git 😆

**Comment by ymherklotz** [comment]
Cool, thanks!
