### ISSUE TITLE
LAB2: Valid expression 12 giving invalid token 

### ISSUE THREAD

**Issue by ZackReeves** [LangProc/langproc-2021-lab#74]
For the following expression, I am getting the output invalid token however, all the aspects are defined in the lex file and all other tests work as expected.

exp(z) * sqrt( log(1.0/x) )

Any thoughts on why it is not lexing correctly?

**Comment by ymherklotz** [comment]
Do you have the `/` token defined in the lexer? Can you, for example, parse the following?

```
1/2
```

**Comment by ZackReeves** [comment]
Ah yes, I didn't see that it wasn't included. Thanks for the help :)
