### ISSUE TITLE
No personal GitHub repository for my coursework

### ISSUE THREAD

**Issue by VincentJue** [LangProc/langproc-2021-lab#79]
Hello, I don't have a personal GitHub repository for my coursework. My teammate's school username is jy920 and our group name is GroupName. My teammate has already been invited to the coursework repository. Thank you.

**Comment by VincentJue** [comment]
![image](https://user-images.githubusercontent.com/97638517/152884026-ccc11284-77ba-4a1d-8a16-59308d98c8a0.png)
Also I found this issue when testing my code. Already passed all the tests in WSL but I want to make the codes are perfectly fine so try to run them in the vagrant environment.

**Comment by ymherklotz** [comment]
I've invited you now.
