### ISSUE TITLE
Submission problem(Git pull and push)

### ISSUE THREAD

**Issue by ZihaoX3** [LangProc/langproc-2021-lab#82]
Hi,
I tried to submit my labs and i followed every instructions but there is no changes in the my own github area. And i check for my repositories and the one for langproc-2021-lab-zx1420(with my name) is not there. 
![image](https://user-images.githubusercontent.com/73709429/153220746-a666e13e-f9c5-44ef-8e93-435673970e1b.png)

I tried to do "git clone https://github.com/LangProc/langproc-2021-lab-${LOGIN}.git" "git remote add spec https://github.com/LangProc/langproc-2021-lab.git" "git remote -v" "git pull spec master" but there is no changes.

I tried to git push  and pull and it said it finished update but there is no changes.

I can access the website for  langproc-2021-lab-zx1420 but there is no commits for those action i had.

I think i haven't do the push for my lab1 still.

What should i do?

**Comment by johnwickerson** [comment]
You need to replace `${LOGIN}` with `zx1420`.
