### ISSUE TITLE
cannot vagrant up on Mac

### ISSUE THREAD

**Issue by charlie-ccw** [LangProc/langproc-2021-lab#83]
I am trying to set up another virtual machine on my Mac laptop, but when i type vagrant up, it says:

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "e01c2b4a-e739-4643-b435-92c7903de048", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'langproc-2021-lab-cc1420_default_1644447043485_56360' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

what should i do to deal with it

**Comment by ymherklotz** [comment]
To get rid of it, you should be able to do:

```
vagrant destroy
```

Then you can create a new VM.
