### ISSUE TITLE
Where in Teams are we supposed to submit the commit hashes?

### ISSUE THREAD

**Issue by MichalPalic** [LangProc/langproc-2021-lab#9]
Hello,
I am having difficulty following the submission procedure and would appreciate clarification on the following step:
_7. Submit the hash via Teams. _
Could you please elaborate on where we're expected to submit / to whom we're supposed to send the hashes?
Sincerely,
Michal

**Comment by johnwickerson** [comment]
I’ll make a spreadsheet for you to do this, a bit nearer the deadline.
