### ISSUE TITLE
3-codegen: interpreted language constraint

### ISSUE THREAD

**Issue by vaclavpavlicek** [LangProc/langproc-2021-lab#90]
Hello, I've got two questions regarding the constraints on the interpreted language in lab 3 part 1.

-  Can I assume that the inputted language is always valid?
-  Can I assume that each variable is firstly written and then read? If not, should I return 0 as the default value?

Could you please help me with that?

**Comment by ymherklotz** [comment]
> Can I assume that the inputted language is always valid?

Yes, all inputs will be valid.

> Can I assume that each variable is firstly written and then read? If not, should I return 0 as the default value?

Yes, if a variable has not been written to, then any behaviour is appropriate.

**Comment by vaclavpavlicek** [comment]
Ok thank you!
