### ISSUE TITLE
lab3 question

### ISSUE THREAD

**Issue by mahasch** [LangProc/langproc-2021-lab#92]
Hi, 
I had a question regarding lab 3. 

If you look at the "if" case in ast.hpp, there is the condition, statement 1 (for the if part), but there is no statement 2 (for the else part). 
An if statement is:
`if (condition){
    statement 1;
}
else{
    statement 2
}`

but that isn't the case here: 
inline TreePtr If(TreePtr cond, TreePtr stat1)
{ return std::make_shared<Tree>("If", **cond, stat1**); }

What is strange is when you access branches[2] (so stat2), even though it doesn't exist, it does not throw an error. I am struggling to visualise this tree and understanding why this works. Can you please explain this?

------------------------------------------------------------------------------------------------------------------------------
Also, I wanted to clarify if this is the correct way to think about this: 
In the ast_compile.cpp file, you only print out the assembly to std::cout, and the VM interprets and translates it into machine level code (so it basically parses the output from the ast_compile.cpp file and interprets that)?

The reason I am unsure is because of these  statements: 
`    }else if( regex_match( program->type, reId ) ){
        std::string zero = makeName("zero");
        std::cout<<"const "<<zero<<" 0"<<std::endl;
        std::cout<<"add "<<destReg<<" "<<program->type<<" `"<<zero<<std::endl;`

in  reId, you don't actually seem to be calcuating or assigning anything, you just print to std::out. Similarly with the other ones, you don't calculate anything - you just print.
Can you please clarify this? 
Thank you

**Comment by BPulmannova** [comment]
Hi,
1) I also originally assumed those inline functions are being used for building the AST, but a global search reveals that none of them is ever called. Instead, `ParseImpl` function in `ast_parse.hpp` always creates a node by using a constructor with `type`, `value`, and `branches` parameters. It is the following line:
`return std::make_pair(std::make_shared<Tree>(type, value, branches),pos);`
and `pos` is used to keep track of the position in the vector of tokens.

2) Yes - the test script does both steps (generating assembly and executing the assembly using the vm). You can recreate this manually by e.g. running:
`./bin/compiler test/programs/add_params/in.code.txt > add_params.s`
`./bin/vm add_params.s 10 7`
Note that once you run the generated assembly on the vm you also need to provide potential parameters/input, while compiler only needs the source code - at compile time, it has no idea what inputs will the assembly be dynamically executed with.

**Comment by mahasch** [comment]
I see, thank you so much for explaining how this works! I understand now!
